apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  #namespace: roboshop
spec:
  containers:
    - name: hello-pod
      image: nginx
      ports:
        - containerPort: 80
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: devops-config
            key: course
      - name: learner
        valueFrom:
          configMapKeyRef:
            name: devops-config
            key: learner
